kind: Deployment
apiVersion: apps/v1
metadata:
  name: notes-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:
        - name: notes-app
          image: keenzieelynn/notes-app
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always